### test
GET http://localhost:8009/test


### test
GET http://localhost:8009/convert-bnb-msg



### listSignals
GET http://localhost:8009/signal/list



### keepAlive
GET http://localhost:8009/unit/socket/keepalive/ppp

### socketClose
GET http://localhost:8009/unit/socket/close/ppp

### getLogs
GET http://localhost:8009/unit/logs/ppp

### cleanLogs
GET http://localhost:8009/unit/clean-log/ppp